### ISSUE TITLE
prepare demo

### ISSUE THREAD

**Issue by TomasTomecek** [container-images/dnf-modularity-prototype#5]
We should also prepare a demo, ideally using boltron compose, something like:

1. list modules
2. enable module
3. install module
4. install package
5. ...

**Comment by mhatina** [comment]
Demo can be found in [copr repo](https://copr.fedorainfracloud.org/coprs/mhatina/DNF-Modules/)

**Comment by TomasTomecek** [comment]
Wow, that's neat! And pretty much what I'm asking for here.

It should also be something that people will be able to do themselves using the image in this repo -- so using real boltron compose. @mhatina Martin, will you be able to re-record the demo using boltron?

**Comment by mhatina** [comment]
I don't think that it would benefit people. Right now they can look at the demo, see how dnf works and then they have to think what they want/need to type and not just blindly copy-paste the command from demo. In my opinion, it is better to 'teach' them this way.
